// packages/ycloud-react/src/context.ts
import { createContext, createElement, type ReactNode, useContext, useMemo } from 'react';
import { YCloudIconsProps } from './types';

type YCloudConfig = {
  size: number;
  color: string;
  strokeWidth: number;
  absoluteStrokeWidth: boolean;
  className: string;
};

const YCloudContext = createContext<YCloudIconsProps>({});

type YCloudIconsProviderProps = {
  children: ReactNode;
} & Partial<YCloudConfig>;

export function YCloudIconsProvider({
  children,
  size,
  color,
  strokeWidth,
  absoluteStrokeWidth,
  className,
}: YCloudIconsProviderProps) {
  const value = useMemo(
    () => ({
      size,
      color,
      strokeWidth,
      absoluteStrokeWidth,
      className,
    }),
    [size, color, strokeWidth, absoluteStrokeWidth, className],
  );

  return createElement(YCloudContext.Provider, { value }, children);
}

export const useYCloudContext = () => useContext(YCloudContext);

// packages/ycloud-solid/src/context.tsx
import { createContext, splitProps, type JSXElement } from 'solid-js';

export const YCloudContext = createContext<{
  size?: number;
  color?: string;
  strokeWidth?: number;
  absoluteStrokeWidth?: boolean;
  class?: string;
}>({
  size: 24,
  color: 'currentColor',
  strokeWidth: 2,
  absoluteStrokeWidth: false,
  class: '',
});

interface YCloudIconsProviderProps {
  children: JSXElement;
  size?: number;
  color?: string;
  strokeWidth?: number;
  absoluteStrokeWidth?: boolean;
  class?: string;
}

export function YCloudIconsProvider(props: YCloudIconsProviderProps) {
  const [value, rest] = splitProps(props, [
    'size',
    'color',
    'strokeWidth',
    'absoluteStrokeWidth',
    'class',
  ]);

  return <YCloudContext.Provider value={value}>{rest.children}</YCloudContext.Provider>;
}
